### PR TITLE
Adding COM Shell API implementation of IFrameworkDialogFactory

### PR DESCRIPTION
**Pull request by daiplusplus**
feat: Adding COM Shell API implementation of IFrameworkDialogFactory

Imports https://github.com/Jehoel/ShellFileDialogs (itself ripped from `Microsoft.WindowsAPICodePack.Shell.dll`) as source into this project and exposes it through an `IFrameworkDialogFactory` implementation. Please see https://github.com/FantasticFiasco/mvvm-dialogs/issues/37 for background and motivation.

Please note the following:

* `CreateMessageBox` isn't supported.
* `FolderBrowserDialogSettings.ShowNewFolderButton` is ignored.
* `FileDialogSettings.AddExtension`, `FileDialogSettings.CheckFileExists`, `FileDialogSettings.CheckPathExists`, and `FileDialogSettings.DefaultExt` are ignored.
* The `IFrameworkDialog.ShowDialog()` implementations never returns `null` - only `true` or `false`.
* I have not written any tests for this code as the current project does not include documentation on how to write tests for WPF components. Feedback and instructions are appreciated.
* I have not pre-squashed my commits because GitHub can squash them during the PR merge: https://blog.github.com/2016-04-01-squash-your-commits/ and because this PR may have further commits after feedback.

### CODE REVIEW

**Comment by daiplusplus** [comment]
BTW the AppVeyor build for .NET Framework 4.5 succeeds but the build for .NET 4.0 fails. This is because of an issue in MvvmDialogs and not my pull-request, see line 112 from the AppVeyor build output:

> The primary reference "MvvmDialogs, Version=5.0.0.0, Culture=neutral, PublicKeyToken=3d3b9708589bc73e, processorArchitecture=MSIL" could not be resolved because it was built against the ".NETFramework,Version=v4.5" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.0". [C:\projects\mvvm-dialogs-contrib\src\net\MvvmDialogs.Contrib.csproj]

The fix for this is to remove .NET 4.0 support. I believe we can safely raise the minimum framework requirement to 4.6.1 now.

**Comment by FantasticFiasco** [comment]
Thanks for the PR!

You are correct, the build error has nothing to do with your code. I'll fix the build error will take a look at the code tonight.

**Comment by FantasticFiasco** [comment]
> The fix for this is to remove .NET 4.0 support. I believe we can safely raise the minimum framework requirement to 4.6.1 now.

I would like to remain compatible with .NET4.0, but haven't found a fix for the problem yet. I will give it another try tomorrow.

> I have not written any tests...

I can write those after we've merged the PR.

> I have not pre-squashed my commits...

No problem, you can do that when we are satisfied with the PR. The reason I wish you to do it and not me when merging back to master is that I wish you to take credit for all changes you've made.

**Comment by daiplusplus** [comment]
BTW, for some reason the line-endings in the files always keep getting reset to `\r\n` even though all of my `.gitconfig` files have an explicit `core.autocrlf = false` setting and there's no `.gitattributes` file. The `.editorconfig` file also specifies `lf`. This is weird. I might need you to reset the endings for me in a sterile environment prior to the merge.

**Comment by FantasticFiasco** [comment]
This day is dedicated to finishing this PR and prepare for the official v1.0.0 NuGet release.

Sorry for the delay, you've caught me in a bad time. Sweden just won against Switzerland yesterday and are now ready to face England in the quarter final. It's the best we've accomplished since 1994 in USA! I was in euphoria last night and couldn't get myself to code, but here I am today...

These are the tasks I foresee before we merge the PR:

- [ ] `CreateMessageBox` isn't supported, but can't we fallback to the default message box instead of not supporting it?
- [ ] The settings that aren't supported by the COM Shell API should be documented in `ComShellDialogFactory`, thus a developer should be able to know this and not be surprised when those settings doesn't affect the opened dialogs
- [x] I will fix the build. I will probably do as you suggest, to remove the support for .NET4.0 in this contrib package. If a user requests .NET4.0 down the road, I can investigate the problem further.
- [x] Add sample applications showing of the feature and enable manual testing of it. I can do this, since it will be the base on which I then add automated UI tests. I'll do this.
- [x] Update `README.md` with a description of the feature, and I'll add a wiki page showing the default dialogs alongside the new cool ones
- [ ] All commits should be squashed into a single one by you, with a message that conforms to the [contributing guidelines](https://github.com/FantasticFiasco/mvvm-dialogs-contrib/blob/master/.github/CONTRIBUTING.md#commit-messages), but we'll do this after all other tasks are finished

Regarding the line endings, I know we have configured Git to use _lf_, but at the same I remember specifying _checkout as crlf but commit in lf_ when installing Git for Windows, and I have no idea whether those two settings play nice together. I'll clone the repo on my Ubuntu, and will report back how the line endings look there.

**Comment by FantasticFiasco** [comment]
I started to compare the default dialogs and the ones used when this feature is enabled, and only found the folder browser dialog to differ. I've posted snapshots of the dialogs [here](https://github.com/FantasticFiasco/mvvm-dialogs-contrib/wiki/COM-shell-dialogs).

Can you verify on your end that only the folder browser dialog differ? If that is the case, perhaps we should fall back to use the default implementation for all dialogs except the folder browser, and rename the feature accordingly.

**Comment by daiplusplus** [comment]
The COM file-open and file-save dialogs are customizable: you can add extra widgets to the lower-half of the dialogs for extra options, for example Notepad uses the area to let the user specify a file encoding - but it's a lot of work to support it and by then you may as well just use the original full Windows Shell "code pack" library.

**Comment by FantasticFiasco** [comment]
Ok, didn't know that. I'll go ahead and update `README.md` and `CHANGELOG.md`.

**Comment by FantasticFiasco** [comment]
I think I am done on my end. Will you let me know when you are done on yours, or if you need me to help you with anything?

**Comment by FantasticFiasco** [comment]
Do you have anything more you would like to do on this PR before we merge this?

**Comment by daiplusplus** [comment]
No, I don't. Thank you.

**Comment by FantasticFiasco** [comment]
An official v1.0.0 is soon available on nuget.org, thank you again for the contribution.

**Pull request merged**
